#!/usr/bin/env bash
# Render .env flags -> gitops/root/values.yaml  (the committed GitOps source of truth).
# Secrets are NOT written here — only the domain + the enable flags.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/_lib.sh
load_env .env

OUT="gitops/root/values.yaml"

cat > "$OUT" <<EOF
# AUTO-GENERATED by scripts/render.sh from .env — do not edit by hand.
# Edit .env and run \`make apply\` (or .\\lab.ps1 apply) to regenerate + push.

domain: ${DOMAIN}

# Per-tool enable flags. ArgoCD installs/prunes based on these.
monitoring:
  enabled: $(yaml_bool "${MONITORING:-false}")
loki:
  enabled: $(yaml_bool "${LOKI:-false}")
jenkins:
  enabled: $(yaml_bool "${JENKINS:-false}")
nexus:
  enabled: $(yaml_bool "${NEXUS:-false}")
EOF

echo "Rendered $OUT:"
sed 's/^/  /' "$OUT"
